# This is the default config.
# If you want to make changes that persist between server reloads/restarts:
#   1. Create a new file called config.yml
#   2. Add new values for each key you want to replace (e.g., hints-enabled: false)
#   3. If a key doesn't exist in config.yml, the plugin will look for it in default.yml


# Allow players to break blocks in others' claims
can-break-in-others-claims: false
# Show hints 
hints-enabled: false
# Time between hints
seconds-between-hints: 600
# Minimum time between intruder alerts
seconds-between-intruder-alerts: 60
# Minimum time between lava immunity messages
seconds-between-lava-immunity-msgs: 60
# Make lavacasting form andesite instead of cobblestone/stone
balance-lavacasting: true
# Give players splash when breaking andesite
andesite-splash-on: true
# Prevent cheat clients from interacting with chests, lecterns, etc. through blocks
disable-freecam-interactions: true
# Make iron golems attack intruders in claimed chunks
golems-guard-claims: true
# Allow players to create master books that update the contents of their copies
enable-master-books: true
# Enable lava immunity for itemless players
enable-lava-immunity: true

# Messages to be shown chronologically the first time a player joins the server
welcome-messages:
  - "&cWelcome! There are 4 things you should know about LecternClaim to get started:"
  - "1) You will need a lectern and a book to claim a chunk, preventing others from placing or breaking blocks."
  - "2) The first line in the book must be 'claim' or it will be considered a normal book."
  - "3) On each line after the first, write the name of a player to add them as a member."
  - "4) Place the book on the lectern to claim the chunk!"

# Hints that are shuffled at server start and shown one by one
hints:
  - "&6Hint #1: &eYou can prevent others from placing or breaking blocks within a chunk by claiming it!"
  - "&6Hint #2: &eWrite a book with \"claim\" and your name in it, then place it on a lectern!"
  - "&6Hint #3: &eType /hints off to stop hints from appearing."
  - "&6Hint #4: &eMaster Books: Signed books can now be edited and will update all copies."
