# Allow players to break blocks in others' claims
can-break-in-others-claims: false
# Show hints 
hints-enabled: false
# Time between hints
seconds-between-hints: 600

# Messages to be shown chronologically the first time a player joins the server
welcome-messages:
  - "&cWelcome! There are 4 things you should know about LecternClaim to get started:"
  - "1) You will need a lectern and a book to claim a chunk, preventing others from placing or breaking blocks."
  - "2) The first line in the book must be 'claim' or it will be considered a normal book."
  - "3) On each line after the first, write the name of a player to add them as a member."
  - "4) Place the book on the lectern to claim the chunk!"

# Hints that are shuffled at server start and shown one by one
hints:
  - "&6Hint #1: &eYou can prevent others from placing or breaking blocks within a chunk by claiming it!"
  - "&6Hint #2: Write a book with \"claim\" and your name in it, then place it on a lectern!"
  - "&6Hint #3: &eType /hints off to stop hints from appearing."
